import { context } from "@cldmv/slothlet/runtime";

function readHead(p, n = 4) {
	try {
		return context.fs.readFileSync(p, "utf8").split(/\r?\n/).slice(0, n).join("\n");
	} catch {
		return null;
	}
}

/**
 * Detect Python pre-commit in a repo.
 *
 * @param {string} repoRoot
 * @param {string|null} gitDir
 * @returns {{kind:"pre-commit",configFile:string|null,headerIn?:string}|null}
 */
export default function preCommit(repoRoot, gitDir) {
	if (!repoRoot) return null;
	const { fs, path } = context;
	const config = path.join(repoRoot, ".pre-commit-config.yaml");
	if (fs.existsSync(config)) return { kind: "pre-commit", configFile: config };
	if (gitDir) {
		const hooksDir = path.join(gitDir, "hooks");
		if (fs.existsSync(hooksDir)) {
			for (const f of fs.readdirSync(hooksDir)) {
				const head = readHead(path.join(hooksDir, f));
				if (head && /File generated by pre-commit/i.test(head)) {
					return { kind: "pre-commit", configFile: null, headerIn: path.join(hooksDir, f) };
				}
			}
		}
	}
	return null;
}
